"""Local setup script for M.R-V.E. — generates Argon2 password hashes and a
session-signing secret, then writes them to .env.

Run once before starting the server:

    python backend/configure_accounts.py

Nothing here is uploaded or transmitted anywhere; it only writes to your
local .env file (already excluded from git by .gitignore).
"""

from __future__ import annotations

import getpass
import re
import secrets
from pathlib import Path

from argon2 import PasswordHasher

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / ".env"

EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

hasher = PasswordHasher()


def prompt_email(label: str, required: bool) -> str:
    while True:
        suffix = "(required)" if required else "(optional, press Enter to skip)"
        value = input(f"{label} email {suffix}: ").strip()
        if not value and not required:
            return ""
        if EMAIL_RE.match(value):
            return value.lower()
        print("  Please enter a valid email address.")


def prompt_password(label: str) -> str:
    while True:
        password = getpass.getpass(f"{label} password (hidden input, min 8 chars): ")
        if len(password) < 8:
            print("  Password must be at least 8 characters.")
            continue
        if password != getpass.getpass("  Confirm password: "):
            print("  Passwords did not match, try again.")
            continue
        return password


def main() -> None:
    print("M.R-V.E. account setup — generates local Argon2 password hashes.\n")

    admin_email = prompt_email("Administrator", required=True)
    admin_hash = hasher.hash(prompt_password("Administrator"))

    print("\nOptional standard-user account (press Enter on email to skip):")
    user_email = prompt_email("Standard user", required=False)
    user_hash = hasher.hash(prompt_password("Standard user")) if user_email else ""

    session_secret = secrets.token_urlsafe(48)

    contents = "\n".join([
        "# M.R-V.E. Master Video Editor — Environment Configuration",
        "# Generated by backend/configure_accounts.py",
        "# SECURITY: This file contains hashed credentials only. Never commit real plaintext passwords.",
        "",
        "# ── Admin Account ───────────────────────────────────────────────────────────",
        f'MVE_ADMIN_EMAIL="{admin_email}"',
        f'MVE_ADMIN_PASSWORD_HASH="{admin_hash}"',
        "",
        "# ── Standard User Account (optional — leave blank to disable) ───────────────",
        f'MVE_USER_EMAIL="{user_email}"',
        f'MVE_USER_PASSWORD_HASH="{user_hash}"',
        "",
        "# ── Session Security (HMAC-SHA256 signing key) ──────────────────────────────",
        f'MVE_SESSION_SECRET="{session_secret}"',
        "",
        "# ── Cookie Security ──────────────────────────────────────────────────────────",
        '# Set to "true" in production (HTTPS). Keep "false" for local HTTP dev.',
        'MVE_COOKIE_SECURE="false"',
        "",
    ])
    ENV_PATH.write_text(contents, encoding="utf-8")
    print(f"\nWrote {ENV_PATH}. Keep it out of version control (already covered by .gitignore).")


if __name__ == "__main__":
    main()